version: '3'
services:
  boomi_atom:
    image: boomi/atom:release
    privileged: true
    environment:
      - URL=https://platform.boomi.com
      - BOOMI_ATOMNAME=atom-docker
      - BOOMI_CONTAINERNAME=atom-docker
      - ATOM_LOCALHOSTID=atom-docker
      - INSTALL_TOKEN=TOKEN_ID
      - BOOMI_ENVIRONMENTID=TOKEN_ID
      - INSTALLATION_DIRECTORY=/var/boomi
    ports:
      - "9090:9090"
    volumes:
      - "./boomi_dir:/var/boomi:consistent"
